on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say, "Hello"
    steps:
    - name: Hello World action step
      id: hello
      uses: l0s/hello-world-javascript-action@v1
      with:
        who-to-greet: 'Octocat'
    - name: Get the output
      run: echo "The time was ${{ steps.hello.outputs.time }}"

